name: Backend Develop CI/CD

on:
  push:
    branches: [develop]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: mvn clean install
        working-directory: ./backend

      - name: Run backend test 
        run: mvn test
        working-directory: ./backend

      - name: Build Docker image
        run: docker build -t prolinkli-backend:develop ./backend

      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag prolinkli-backend:develop ghcr.io/prolinkli/prolinkli-backend:develop
          docker push ghcr.io/prolinkli/prolinkli-backend:develop

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /mnt/sda/prolinkli
            ./deploy.sh dev